######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 26 14:28:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h lcdrange.h
SOURCES += cannonfield.cpp lcdrange.cpp main.cpp
