'''
Created on Mar 29, 2012

@author: Steven
'''
import sqlalchemy
import sqlalchemy.orm

class ShoppingListItem (object):
    
    def __init__(self, listId, name, creationDate, autoGeneratedFlag):
        self.listId = listId
        self.name = name
        self.creationDate = creationDate
        self.autoGeneratedFlag = autoGeneratedFlag
        self.identifier = None
        
    def __repr__(self):
        return "<ShoppingList(%d, %s)" % (self.listId, self.name)
    
class ShoppingListLinkerItem (object):
    
    def __init__(self, listId, itemId, itemDescription, quantity):
        self.listId = listId
        self.itemId = itemId
        self.itemDescription = itemDescription
        self.quantity = quantity
        self.identifier = None
        
    def __repr__(self):
        return "<Linker(%d, %d, %d)>" % (self.listId, self.itemId, self.quantity)

class ShoppingListTable (object):
    '''
    classdocs
    '''

    def __init__(self, model):
        '''
        Constructor
        '''
        self.model = model
        
        shoppingListTable = sqlalchemy.Table('shoppingList', self.model.metadata, \
            sqlalchemy.Column('id', sqlalchemy.Integer, primary_key=True), \
            sqlalchemy.Column('listId', sqlalchemy.Integer, primary_key=True), \
            sqlalchemy.Column('name', sqlalchemy.String(128)), \
            sqlalchemy.Column('creationDate', sqlalchemy.DateTime), \
            sqlalchemy.Column('autoGeneratedFlag', sqlalchemy.Boolean), \
            sqlalchemy.Column('identifier', sqlalchemy.String(16)))
        
        shoppingListLinkerTable = sqlalchemy.Table('shoppingListLinker', self.model.metadata, \
            sqlalchemy.Column('id', sqlalchemy.Integer, primary_key=True), \
            sqlalchemy.Column('listId', sqlalchemy.Integer, primary_key=True), \
            sqlalchemy.Column('itemId', sqlalchemy.BigInteger), \
            sqlalchemy.Column('itemDescription', sqlalchemy.String(128)), \
            sqlalchemy.Column('quantity', sqlalchemy.Integer), \
            sqlalchemy.Column('identifier', sqlalchemy.String(44)))
        
        self.model.metadata.create_all (self.model.engine)
        sqlalchemy.orm.mapper (ShoppingListItem, shoppingListTable)
        sqlalchemy.orm.mapper (ShoppingListLinkerItem, shoppingListLinkerTable)
        
        Session = sqlalchemy.orm.sessionmaker(bind=self.model.engine)
        self.session = Session()
        
        self.listId = 0
        for shoppingList in self.session.query(ShoppingListItem).distinct():
            self.model.controllerObj.addNewShoppingList (shoppingList)
            if self.listId <= shoppingList.listId: 
                self.listId = shoppingList.listId+1 
                
        for linker in self.session.query(ShoppingListLinkerItem).distinct():
            self.model.controllerObj.addNewShoppingListItem (linker)
        
    def addNewShoppingList (self, shoppingList):
        self.session.add(shoppingList)
        self.session.commit()
        
    def returnListByIdentifier (self, identifier):
        return self.session.query(ShoppingListItem).filter(ShoppingListItem.identifier.startswith(identifier)).all()
    
    def returnListItemByIdentifier (self, identifier):
        return self.session.query(ShoppingListLinkerItem).filter(ShoppingListLinkerItem.identifier==identifier).all()
    
    def returnLinkerItem (self, shoppingList, item):
        return self.session.query(ShoppingListLinkerItem).filter((ShoppingListLinkerItem.listId==shoppingList.listId) & \
            (ShoppingListLinkerItem.itemId==item.upc)).all()
            
    def returnCustomLinkerItem (self, shoppingList, description):
        return self.session.query(ShoppingListLinkerItem).filter((ShoppingListLinkerItem.listId==shoppingList.listId) & \
            (ShoppingListLinkerItem.itemDescription==description)).all()
            
    def addNewShoppingListItem (self, linker):
        self.session.add(linker)
        self.session.commit()
        
    def updateShoppingListItem (self):
        self.session.commit()
        
    def removeShoppingList (self, shoppingList):
        self.session.delete(shoppingList)
       
        items = self.session.query(ShoppingListLinkerItem).filter((ShoppingListLinkerItem.listId==shoppingList.listId)).all() 
        for item in items:
            self.session.delete(item)
        
        self.session.commit()
        
    def removeShoppingListItem (self, shoppingListItem):
        self.session.delete(shoppingListItem)
        self.session.commit()
        
    def grantNewListId (self):
        returnValue = self.listId
        self.listId += 1
        
        return returnValue
    
    def populateSuggestedShoppingList (self, shoppingList):
        print 'You are out of luck for now'