package edu.rit.smartFridge.util;

import java.util.Date;
import java.util.List;

import edu.rit.smartFridge.model.InventoryItem;
import edu.rit.smartFridge.model.ShoppingList;
import edu.rit.smartFridge.model.ShoppingListItem;


public class ormliteConnect implements DataConnect
{
	/**
	 * Autogenerated UID for serialization
	 */
	private static final long serialVersionUID = -244775505247558467L;

	public List<ShoppingList> getLists() {
		// TODO Auto-generated method stub
		return null;
	}

	public ShoppingList getList(int listId) {
		// TODO Auto-generated method stub
		return null;
	}

	public ShoppingList populateItems(ShoppingList list) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<InventoryItem> getInventory() {
		// TODO Auto-generated method stub
		return null;
	}

	public List<InventoryItem> getItem(long UPC) {
		// TODO Auto-generated method stub
		return null;
	}

	public int getItemCount(long UPC) {
		// TODO Auto-generated method stub
		return 0;
	}

	public List<Date> getExpirationDates(long UPC) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Date> getPurchaseDates(long UPC) {
		// TODO Auto-generated method stub
		return null;
	}

}
