package edu.rit.smartFridge.util;

import java.util.HashMap;
import java.util.List;

import edu.rit.smartFridge.model.InventoryItem;
import edu.rit.smartFridge.model.ShoppingList;


public class ormliteConnect implements DataConnect
{
	/**
	 * Autogenerated UID for serialization
	 */
	private static final long serialVersionUID = -244775505247558467L;

	public List<ShoppingList> getLists() {
		// TODO Auto-generated method stub
		return null;
	}

	public ShoppingList getList(int listId) {
		// TODO Auto-generated method stub
		return null;
	}

	public ShoppingList populateItems(ShoppingList list) {
		// TODO Auto-generated method stub
		return null;
	}

	public HashMap<String, List<InventoryItem>> getInventory() {
		// TODO Auto-generated method stub
		return null;
	}

}
